---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
##Articles with explicitly stated hypotheses
#total
(100/322)*100
#ASR
(56/139)*100
#AJS
(29/105)*100
#SQ
(15/78)*100


##Articles with required statistics (i.e., articles with at least one reported p-value or reproducible result)
#total
(91/322)*100
#ASR
(53/139)*100
#AJS
(26/105)*100
#SQ
(14/78)*100
```

```{r, include=knitr::is_html_output()}
library(DiagrammeR)
library(DiagrammeRsvg)
library(magrittr)
library(rsvg)

grViz("digraph{

      graph[rankdir = LR]
  
      node[shape = rectangle]
  
      subgraph cluster_0 {
        graph[shape = rectangle]
        style = rounded
       
        label = 'Total number of articles\\n (n = 322)'
        node[shape = rectangle, margin = 0.25]
        A[label = 'ASR = 139', fixedsize = true, width = 1.35, height = 0.7]
        B[label = 'AJS = 105', fixedsize = true, width = 1.35, height = 0.7]
        C[label = 'SQ = 78', fixedsize = true, width = 1.35, height = 0.7]
      }
  
      subgraph cluster_1 {
         graph[shape = rectangle]
         style = rounded
         
         label = 'Articles with explicitly stated hypotheses\\n (n = 100, 31.1%)'
         node[shape = rectangle, margin = 0.25]
         D[label = 'ASR = 56 (40.3%)', fixedsize = true, width = 1.8, height = 0.7]
         E[label = 'AJS = 29 (27.6%)', fixedsize = true, width = 1.8, height = 0.7]
         F[label = 'SQ = 15 (19.2%)', fixedsize = true, width = 1.8, height = 0.7]
      }
      
      subgraph cluster_2 {
        graph[shape = rectangle]
        style = rounded
       
        label = 'Articles with required statistics\\n (n = 91, 28.3%)'
        node[shape = rectangle, margin = 0.25]
        G[label = 'ASR = 53 (32.1%)', fixedsize = true, width = 1.8, height = 0.7]
        H[label = 'AJS = 26 (24.8%)', fixedsize = true, width = 1.8, height = 0.7]
        I[label = 'SQ = 14 (18.0%)', fixedsize = true, width = 1.8, height = 0.7]
      }
      
      edge[color = black, arrowhead = vee, arrowsize = 1.25]
      A -> D
      B -> E
      C -> F
      D -> G
      E -> H
      F -> I
           }")
```
  
